// ActionTypes.ts
export const SET_RESUME_TEMPLATE = "SET_RESUME_TEMPLATE";
// Personal details
export const SET_RESUME_NAME = "SET_RESUME_NAME";
export const SET_RESUME_LASTNAME = "SET_RESUME_LASTNAME";
export const SET_RESUME_EMAIL = "SET_RESUME_EMAIL";
export const SET_RESUME_PHONE = "SET_RESUME_PHONE";
export const SET_RESUME_JOBTITLE = "SET_RESUME_JOBTITLE";
export const SET_RESUME_ADRESS = "SET_RESUME_ADRESS";
export const SET_RESUME_SOCIALLINKS = "SET_RESUME_SOCIALLINKS";

// Expirience
export const SET_RESUME_COMPANYNAME = "SET_RESUME_COMPANYNAME";
export const SET_RESUME_POSITION = "SET_RESUME_POSITION";
export const SET_RESUME_STARTDATE = "SET_RESUME_STARTDATE";
export const SET_RESUME_ENDDATE = "SET_RESUME_ENDDATE";
