// ActionTypes.ts
export const SET_RESUME_TEMPLATE = "SET_RESUME_TEMPLATE";
// Personal details
export const SET_RESUME_NAME = "SET_RESUME_NAME";
export const SET_RESUME_LASTNAME = "SET_RESUME_LASTNAME";
export const SET_RESUME_EMAIL = "SET_RESUME_EMAIL";
export const SET_RESUME_PHONE = "SET_RESUME_PHONE";
export const SET_RESUME_JOBTITLE = "SET_RESUME_JOBTITLE";
export const SET_RESUME_ADRESS = "SET_RESUME_ADRESS";
export const SET_RESUME_SOCIALLINKS = "SET_RESUME_SOCIALLINKS";
export const SET_RESUME_SKILLS = "SET_RESUME_SKILLS";
export const SET_RESUME_ABOUT = "SET_RESUME_ABOUT";

// Expirience
export const SET_RESUME_COMPANYNAME = "SET_RESUME_COMPANYNAME";
export const SET_RESUME_POSITION = "SET_RESUME_POSITION";
export const SET_RESUME_STARTDATE = "SET_RESUME_STARTDATE";
export const SET_RESUME_ENDDATE = "SET_RESUME_ENDDATE";
export const SET_RESUME_ABOUTEXPIRIENCE = "SET_RESUME_ABOUTEXPIRIENCE";

// Education
export const SET_RESUME_EDUCATIONNAME = "SET_RESUME_EDUCATIONNAME";
export const SET_RESUME_EDUCATIONPOSITION = "SET_RESUME_EDUCATIONPOSITION";
export const SET_RESUME_EDUCATION_STARTDATE = "SET_RESUME_EDUCATION_STARTDATE";
export const SET_RESUME_EDUCATION_ENDDATE = "SET_RESUME_EDUCATION_ENDDATE";
export const SET_RESUME_ABOUTEDUCATION = "SET_RESUME_ABOUTEDUCATION";

// Add Additional Section
export const SET_RESUME_LANGUAGES = "SET_RESUME_LANGUAGES";
export const SET_RESUME_INTERESTS = "SET_RESUME_INTERESTS";
export const SET_RESUME_VOLUNTEERING_ACTIVITYNAME = "SET_RESUME_VOLUNTEERING_ACTIVITYNAME";
export const SET_RESUME_VOLUNTEERING_ADDRESS = "SET_RESUME_VOLUNTEERING_ADDRESS";
export const SET_RESUME_VOLUNTEERING_STARTDATE = "SET_RESUME_VOLUNTEERING_STARTDATE";
export const SET_RESUME_VOLUNTEERING_ENDDATE = "SET_RESUME_VOLUNTEERING_ENDDATE";
export const SET_RESUME_VOLUNTEERING_ABOUT = "SET_RESUME_VOLUNTEERING_ABOUT";
